spring.application.name=sistema-notas
# URL de conexão: aponta para o localhost, porta padrão 5432 e o banco escoladti
spring.datasource.url=jdbc:postgresql://localhost:5432/escoladti
spring.datasource.username=postgres
spring.datasource.password=1819

# Estratégia do Hibernate (update cria as tabelas automaticamente se elas não existirem)
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do terminal os comandos SQL que o Spring está executando (ótimo para estudar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do banco de dados
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Dá permissão para o Hibernate criar e atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra no terminal os comandos SQL que o Java está executando no PostgreSQL (ótimo para ver a mágica acontecendo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true